# -*- coding: utf-8 -*-
"""BT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ryzljtscdrt-i-eNOjOrvqOSuBfLoQok
"""

from google.colab import drive
drive.mount('/content/drive')
file_path='/content/drive/MyDrive/AI món ăn'

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.utils import load_img, img_to_array
import matplotlib.pyplot as plt
import numpy as np
from keras.datasets import mnist
from keras import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.2  # ✅ thêm dòng này
)

img_width, img_height = 200,200

import os

# Define the path to your folder in Google Drive
train_dir = '/content/drive/MyDrive/AI món ăn'

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=16,          # ✅ sửa từ 250 → 16
    class_mode='categorical',
    subset='training'       # ✅ thêm
)

val_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=16,
    class_mode='categorical',
    subset='validation'     # ✅ thêm
)

model2 = Sequential([
    Conv2D(32,(3,3), activation='relu', input_shape=(img_width,img_height,3)),
    MaxPooling2D((2,2)),
    Conv2D(64,(3,3), activation='relu'),
    MaxPooling2D((2,2)),
    Conv2D(128,(3,3), activation='relu', padding='same'),
    MaxPooling2D((2,2)),
    Flatten(), # Flatten the output of the convolutional layers
    Dense(128, activation='relu'), # Example Dense layer
    Dropout(0.5), # Example Dropout layer
    Dense(train_generator.num_classes, activation='softmax') # Final Dense layer for classification
])

model2.compile(optimizer='adam',
               loss='categorical_crossentropy',
               metrics=['accuracy'])
model2.summary()

epochs_num = 110  # ✅ tăng từ 40 → 50
history2 = model2.fit(
    train_generator,
    epochs=epochs_num,
    validation_data=val_generator  # ✅ thêm
)

plt.plot

from keras.utils import load_img
path ='/content/images.jpg'

img2=load_img(path, target_size=(img_width, img_height))
plt.imshow(img2)
plt.show()

img2=np.array(img2)
img2=img2.reshape(1,img_width,img_height,3)
img2=img2.astype('float32')/255

predictions=np.argmax(model2.predict(img2))


class_lables={v:k for k, v in train_generator.class_indices.items()}
food_name=class_lables[predictions]
print(f"Mon tien doan: {food_name}")

